# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3c8ba0018ffd860c13d5046fe3026df4dc321408854980cec9ae94a51d129b65b9457cd0c356d2b9aceddaf85c162d7b02e791a61c9f7b2c2fb04fd938b0dad

test:
  secret_key_base: 2f83bf74dfb66b7e7a661d528395d103b3fbc9cc8163275f7d44a13b41563962f84d8506e110c7ce4b401f5a1ab8eb17096bf5e93b9bae2aa4a443fafac92194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
